//! Pure manifest + KIND-config emitters.
//!
//! Every function here is a pure projection of [`Answers`] (or a small typed
//! input) to a YAML/string artifact — no I/O. The provisioning orchestrator
//! ([`crate::command::app`]) writes these to the workspace and `kubectl apply`s
//! them through the [`CommandRunner`] seam. Keeping the emitters pure means the
//! exact rendered YAML is asserted in unit tests, the same discipline the
//! migration-assistant CLI uses for its helm/manifest builders.
//!
//! Image references intentionally use public registries (docker.elastic.co,
//! docker.io/opensearchproject, public.ecr.aws) pinned to the versions the
//! Migration Assistant 3.3.1 release targets.

use crate::model::{Answers, ClientApp, SnapshotStorage, SourceEngine};
use crate::util::yaml_quote;

/// The Kubernetes namespace every harness-provisioned workload lives in.
pub const NAMESPACE: &str = "ma-demo";

/// Resolve the container image for a source engine + version.
pub fn source_image(engine: SourceEngine, version: &str) -> String {
    match engine {
        SourceEngine::Elasticsearch => {
            format!("docker.elastic.co/elasticsearch/elasticsearch:{version}")
        }
        SourceEngine::OpenSearch => format!("opensearchproject/opensearch:{version}"),
        SourceEngine::Solr => format!("solr:{version}"),
    }
}

/// Resolve the target OpenSearch image for a version.
pub fn target_image(version: &str) -> String {
    format!("opensearchproject/opensearch:{version}")
}

/// A KIND cluster config that maps a NodePort to a host port, so the operator
/// (and the Migration Assistant) can reach the cluster from the host. `role`
/// distinguishes source from target; `host_port` is the port published on the
/// host's loopback.
pub fn kind_config(cluster_name: &str, host_port: u16, node_port: u16) -> String {
    format!(
        "# KIND cluster config for the {cluster_name} role.\n\
         # Generated by migration-assistant-demo — do not edit by hand.\n\
         kind: Cluster\n\
         apiVersion: kind.x-k8s.io/v1alpha4\n\
         name: {cluster_name}\n\
         nodes:\n\
         \x20 - role: control-plane\n\
         \x20   extraPortMappings:\n\
         \x20     - containerPort: {node_port}\n\
         \x20       hostPort: {host_port}\n\
         \x20       protocol: TCP\n"
    )
}

/// The Namespace manifest.
pub fn namespace() -> String {
    format!("apiVersion: v1\nkind: Namespace\nmetadata:\n  name: {NAMESPACE}\n")
}

/// A single-node Elasticsearch/OpenSearch StatefulSet + Service for the source.
///
/// Security is disabled (single-node demo) and discovery is single-node. When
/// `plugins` are requested the container's command is overridden to install
/// them via the engine's plugin CLI (into the engine's own plugins dir, so they
/// actually load) and then `exec` the image's real entrypoint — preserving the
/// bundled plugins, unlike a volume overlay. The Service exposes a NodePort so a
/// KIND extraPortMapping can publish it to the host.
pub fn http_source(answers: &Answers) -> String {
    let engine = answers
        .source_engine
        .expect("http_source requires an HTTP search engine");
    let version = answers.source_version.as_deref().unwrap_or("latest");
    let image = source_image(engine, version);
    let (env, name) = match engine {
        SourceEngine::Elasticsearch => (es_env(), "source-elasticsearch"),
        SourceEngine::OpenSearch => (os_env(), "source-opensearch"),
        SourceEngine::Solr => unreachable!("solr is not an http source"),
    };

    // When plugins are requested, override the command to install-then-exec;
    // otherwise let the image's default entrypoint run.
    let command = plugin_command(engine, &answers.source_plugins);

    format!(
        "apiVersion: v1\n\
         kind: Service\n\
         metadata:\n\
         \x20 name: {name}\n\
         \x20 namespace: {NAMESPACE}\n\
         spec:\n\
         \x20 type: NodePort\n\
         \x20 selector:\n\
         \x20   app: {name}\n\
         \x20 ports:\n\
         \x20   - name: http\n\
         \x20     port: 9200\n\
         \x20     targetPort: 9200\n\
         \x20     nodePort: 30920\n\
         ---\n\
         apiVersion: apps/v1\n\
         kind: StatefulSet\n\
         metadata:\n\
         \x20 name: {name}\n\
         \x20 namespace: {NAMESPACE}\n\
         spec:\n\
         \x20 serviceName: {name}\n\
         \x20 replicas: 1\n\
         \x20 selector:\n\
         \x20   matchLabels:\n\
         \x20     app: {name}\n\
         \x20 template:\n\
         \x20   metadata:\n\
         \x20     labels:\n\
         \x20       app: {name}\n\
         \x20   spec:\n\
         \x20     containers:\n\
         \x20       - name: {name}\n\
         \x20         image: {image}\n\
         {command}\
         \x20         ports:\n\
         \x20           - containerPort: 9200\n\
         \x20         env:\n\
         {env}",
    )
}

/// The ES single-node env block (security off, single discovery, bounded heap).
fn es_env() -> String {
    [
        ("discovery.type", "single-node"),
        ("xpack.security.enabled", "false"),
        ("ES_JAVA_OPTS", "-Xms512m -Xmx512m"),
    ]
    .iter()
    .map(|(k, v)| env_pair(k, v))
    .collect::<Vec<_>>()
    .join("")
}

/// The OpenSearch single-node env block.
fn os_env() -> String {
    [
        ("discovery.type", "single-node"),
        ("DISABLE_SECURITY_PLUGIN", "true"),
        ("OPENSEARCH_JAVA_OPTS", "-Xms512m -Xmx512m"),
        ("OPENSEARCH_INITIAL_ADMIN_PASSWORD", "Demo_Admin_1234!"),
    ]
    .iter()
    .map(|(k, v)| env_pair(k, v))
    .collect::<Vec<_>>()
    .join("")
}

/// One `env:` list entry (12-space indented to sit under the container).
fn env_pair(name: &str, value: &str) -> String {
    format!(
        "\x20           - name: {name}\n\x20             value: {}\n",
        yaml_quote(value)
    )
}

/// A `command:` override that installs each requested plugin into the engine's
/// own plugins dir, then `exec`s the image's real entrypoint so the bundled
/// plugins are preserved and the newly-installed ones load. Returns empty
/// string (no override → default entrypoint) when no plugins were requested.
///
/// The plugin CLI and the entrypoint to exec differ per engine:
///
/// - Elasticsearch: `elasticsearch-plugin` + `/usr/local/bin/docker-entrypoint.sh eswrapper`
/// - OpenSearch: `opensearch-plugin` + `./opensearch-docker-entrypoint.sh`
///
/// Both run as a single `sh -c` so the install completes before the server boots.
fn plugin_command(engine: SourceEngine, plugins: &[String]) -> String {
    if plugins.is_empty() {
        return String::new();
    }
    let (cli, entrypoint) = match engine {
        SourceEngine::Elasticsearch => (
            "elasticsearch-plugin",
            "exec /usr/local/bin/docker-entrypoint.sh eswrapper",
        ),
        SourceEngine::OpenSearch => (
            "opensearch-plugin",
            "exec ./opensearch-docker-entrypoint.sh",
        ),
        SourceEngine::Solr => unreachable!("solr is not an http source"),
    };
    let installs = plugins
        .iter()
        .map(|p| format!("{cli} install --batch {p}"))
        .collect::<Vec<_>>()
        .join(" && ");
    let script = format!("{installs} && {entrypoint}");
    format!(
        "\x20         command: [\"sh\", \"-c\", {}]\n",
        yaml_quote(&script)
    )
}

/// A single-node Solr Deployment + Service for the source (backfill-only path).
pub fn solr_source(version: &str) -> String {
    let image = format!("solr:{version}");
    format!(
        "apiVersion: v1\n\
         kind: Service\n\
         metadata:\n\
         \x20 name: source-solr\n\
         \x20 namespace: {NAMESPACE}\n\
         spec:\n\
         \x20 type: NodePort\n\
         \x20 selector:\n\
         \x20   app: source-solr\n\
         \x20 ports:\n\
         \x20   - name: http\n\
         \x20     port: 8983\n\
         \x20     targetPort: 8983\n\
         \x20     nodePort: 30983\n\
         ---\n\
         apiVersion: apps/v1\n\
         kind: Deployment\n\
         metadata:\n\
         \x20 name: source-solr\n\
         \x20 namespace: {NAMESPACE}\n\
         spec:\n\
         \x20 replicas: 1\n\
         \x20 selector:\n\
         \x20   matchLabels:\n\
         \x20     app: source-solr\n\
         \x20 template:\n\
         \x20   metadata:\n\
         \x20     labels:\n\
         \x20       app: source-solr\n\
         \x20   spec:\n\
         \x20     containers:\n\
         \x20       - name: solr\n\
         \x20         image: {image}\n\
         \x20         ports:\n\
         \x20           - containerPort: 8983\n\
         \x20         args: [\"solr-precreate\", \"demo\"]\n"
    )
}

/// Dispatch to the right source manifest for the chosen engine.
pub fn source(answers: &Answers) -> String {
    match answers.source_engine {
        Some(SourceEngine::Solr) => {
            solr_source(answers.source_version.as_deref().unwrap_or("9.7.0"))
        }
        Some(_) => http_source(answers),
        None => String::new(),
    }
}

/// The target OpenSearch StatefulSet + Service (when provisioning a target).
pub fn target(version: &str) -> String {
    let image = target_image(version);
    let env = os_env();
    format!(
        "apiVersion: v1\n\
         kind: Service\n\
         metadata:\n\
         \x20 name: target-opensearch\n\
         \x20 namespace: {NAMESPACE}\n\
         spec:\n\
         \x20 type: NodePort\n\
         \x20 selector:\n\
         \x20   app: target-opensearch\n\
         \x20 ports:\n\
         \x20   - name: http\n\
         \x20     port: 9200\n\
         \x20     targetPort: 9200\n\
         \x20     nodePort: 30920\n\
         ---\n\
         apiVersion: apps/v1\n\
         kind: StatefulSet\n\
         metadata:\n\
         \x20 name: target-opensearch\n\
         \x20 namespace: {NAMESPACE}\n\
         spec:\n\
         \x20 serviceName: target-opensearch\n\
         \x20 replicas: 1\n\
         \x20 selector:\n\
         \x20   matchLabels:\n\
         \x20     app: target-opensearch\n\
         \x20 template:\n\
         \x20   metadata:\n\
         \x20     labels:\n\
         \x20       app: target-opensearch\n\
         \x20   spec:\n\
         \x20     containers:\n\
         \x20       - name: opensearch\n\
         \x20         image: {image}\n\
         \x20         ports:\n\
         \x20           - containerPort: 9200\n\
         \x20         env:\n\
         {env}"
    )
}

/// LocalStack S3 (the simulated snapshot repository) — Deployment + Service.
pub fn localstack() -> String {
    format!(
        "apiVersion: v1\n\
         kind: Service\n\
         metadata:\n\
         \x20 name: localstack\n\
         \x20 namespace: {NAMESPACE}\n\
         spec:\n\
         \x20 selector:\n\
         \x20   app: localstack\n\
         \x20 ports:\n\
         \x20   - name: edge\n\
         \x20     port: 4566\n\
         \x20     targetPort: 4566\n\
         ---\n\
         apiVersion: apps/v1\n\
         kind: Deployment\n\
         metadata:\n\
         \x20 name: localstack\n\
         \x20 namespace: {NAMESPACE}\n\
         spec:\n\
         \x20 replicas: 1\n\
         \x20 selector:\n\
         \x20   matchLabels:\n\
         \x20     app: localstack\n\
         \x20 template:\n\
         \x20   metadata:\n\
         \x20     labels:\n\
         \x20       app: localstack\n\
         \x20   spec:\n\
         \x20     containers:\n\
         \x20       - name: localstack\n\
         \x20         image: localstack/localstack:4.3.0\n\
         \x20         ports:\n\
         \x20           - containerPort: 4566\n\
         \x20         env:\n\
         \x20           - name: SERVICES\n\
         \x20             value: \"s3\"\n\
         \x20           - name: DEFAULT_REGION\n\
         \x20             value: \"us-east-1\"\n"
    )
}

/// A Locust load-generation Deployment that drives index+search traffic at the
/// source service. The locustfile is mounted from a ConfigMap.
pub fn locust(source_host: &str) -> String {
    let locustfile = locustfile(source_host);
    let cm_data = crate::util::indent(&locustfile, 4);
    format!(
        "apiVersion: v1\n\
         kind: ConfigMap\n\
         metadata:\n\
         \x20 name: locust-script\n\
         \x20 namespace: {NAMESPACE}\n\
         data:\n\
         \x20 locustfile.py: |\n\
         {cm_data}\n\
         ---\n\
         apiVersion: apps/v1\n\
         kind: Deployment\n\
         metadata:\n\
         \x20 name: locust\n\
         \x20 namespace: {NAMESPACE}\n\
         spec:\n\
         \x20 replicas: 1\n\
         \x20 selector:\n\
         \x20   matchLabels:\n\
         \x20     app: locust\n\
         \x20 template:\n\
         \x20   metadata:\n\
         \x20     labels:\n\
         \x20       app: locust\n\
         \x20   spec:\n\
         \x20     containers:\n\
         \x20       - name: locust\n\
         \x20         image: locustio/locust:2.31.8\n\
         \x20         args: [\"-f\", \"/script/locustfile.py\", \"--headless\", \"-u\", \"10\", \"-r\", \"2\", \"--host\", \"http://{source_host}:9200\"]\n\
         \x20         volumeMounts:\n\
         \x20           - name: script\n\
         \x20             mountPath: /script\n\
         \x20     volumes:\n\
         \x20       - name: script\n\
         \x20         configMap:\n\
         \x20           name: locust-script\n"
    )
}

/// The locustfile body — a minimal index+search workload against an ES/OS REST
/// endpoint. Kept dependency-free (pure stdlib `requests` shipped in the locust
/// image).
pub fn locustfile(source_host: &str) -> String {
    format!(
        "from locust import HttpUser, task, between\n\
         import json, random\n\
         \n\
         # Drives index + search traffic at {source_host}:9200 so the migration\n\
         # has live application load to capture and replay.\n\
         class SearchUser(HttpUser):\n\
         \x20   wait_time = between(0.5, 2.0)\n\
         \n\
         \x20   @task(3)\n\
         \x20   def index_doc(self):\n\
         \x20       doc = {{\"user\": random.randint(1, 1000), \"msg\": \"demo\", \"ts\": random.random()}}\n\
         \x20       self.client.post(\"/demo-logs/_doc\", json=doc, name=\"index\")\n\
         \n\
         \x20   @task(5)\n\
         \x20   def search(self):\n\
         \x20       q = {{\"query\": {{\"match\": {{\"msg\": \"demo\"}}}}}}\n\
         \x20       self.client.get(\"/demo-logs/_search\", data=json.dumps(q),\n\
         \x20                       headers={{\"Content-Type\": \"application/json\"}}, name=\"search\")\n"
    )
}

/// A tiny always-on sample search application: a busybox loop issuing a
/// representative query every few seconds, so the operator sees a "live app"
/// during migration. Kept minimal — its purpose is to be visibly running.
pub fn sample_search_app(source_host: &str) -> String {
    let script = format!(
        "while true; do wget -qO- 'http://{source_host}:9200/demo-logs/_search?q=msg:demo&size=1' || true; sleep 5; done"
    );
    format!(
        "apiVersion: apps/v1\n\
         kind: Deployment\n\
         metadata:\n\
         \x20 name: sample-search-app\n\
         \x20 namespace: {NAMESPACE}\n\
         spec:\n\
         \x20 replicas: 1\n\
         \x20 selector:\n\
         \x20   matchLabels:\n\
         \x20     app: sample-search-app\n\
         \x20 template:\n\
         \x20   metadata:\n\
         \x20     labels:\n\
         \x20       app: sample-search-app\n\
         \x20   spec:\n\
         \x20     containers:\n\
         \x20       - name: client\n\
         \x20         image: busybox:1.36\n\
         \x20         command: [\"sh\", \"-c\", {}]\n",
        yaml_quote(&script)
    )
}

/// A Kubernetes Job that seeds sample indices into the source over its REST
/// API, so the migration has real data to move. Self-contained: a small `curl`
/// image waits for the source to be green, then bulk-loads a `demo-logs` index
/// with a few hundred documents via the `_bulk` API. Deliberately dependency-
/// free (no DataGenerator/console image, which needs a migration config) — the
/// goal is simply visible, migratable data on the source.
pub fn data_seed_job(source_host: &str) -> String {
    // Wait for the source, then generate ~300 bulk docs with a tiny awk loop and
    // POST them. ES and OpenSearch share the `_bulk` newline-delimited format.
    let script = format!(
        "echo 'waiting for {source_host}…'; \
         until curl -sf http://{source_host}:9200 >/dev/null 2>&1; do sleep 3; done; \
         echo 'source up; seeding demo-logs'; \
         awk 'BEGIN{{for(i=0;i<300;i++){{\
print \"{{\\\"index\\\":{{}}}}\"; \
print \"{{\\\"user\\\":\" (i%100) \",\\\"msg\\\":\\\"demo log line \" i \"\\\",\\\"level\\\":\\\"info\\\"}}\"}}}}' > /tmp/bulk.ndjson; \
         curl -s -H 'Content-Type: application/x-ndjson' \
           -XPOST 'http://{source_host}:9200/demo-logs/_bulk?refresh=true' \
           --data-binary @/tmp/bulk.ndjson > /tmp/out.json; \
         echo 'seeded; doc count:'; \
         curl -s 'http://{source_host}:9200/demo-logs/_count'"
    );
    format!(
        "apiVersion: batch/v1\n\
         kind: Job\n\
         metadata:\n\
         \x20 name: data-seed\n\
         \x20 namespace: {NAMESPACE}\n\
         spec:\n\
         \x20 backoffLimit: 3\n\
         \x20 template:\n\
         \x20   spec:\n\
         \x20     restartPolicy: Never\n\
         \x20     containers:\n\
         \x20       - name: data-seed\n\
         \x20         image: curlimages/curl:8.10.1\n\
         \x20         command: [\"sh\", \"-c\", {}]\n",
        yaml_quote(&script)
    )
}

/// Which client manifests apply for the selected client apps, paired with a
/// short label. The orchestrator writes + applies each.
pub fn client_manifests(answers: &Answers, source_host: &str) -> Vec<(&'static str, String)> {
    let mut out = Vec::new();
    if answers.has_client(ClientApp::Locust) {
        out.push(("locust", locust(source_host)));
    }
    if answers.has_client(ClientApp::SampleSearchApp) {
        out.push(("sample-search-app", sample_search_app(source_host)));
    }
    out
}

/// Whether snapshot storage manifests should be emitted for this plan.
pub fn needs_localstack(answers: &Answers) -> bool {
    answers.snapshot_storage == Some(SnapshotStorage::LocalStack)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{SnapshotStorage, SourceEngine, Target, TargetMode};

    fn es_answers() -> Answers {
        let mut a = Answers::new();
        a.target = Some(Target::Local);
        a.source_engine = Some(SourceEngine::Elasticsearch);
        a.source_version = Some("7.10.2".into());
        a
    }

    #[test]
    fn source_image_paths_are_correct() {
        assert_eq!(
            source_image(SourceEngine::Elasticsearch, "7.10.2"),
            "docker.elastic.co/elasticsearch/elasticsearch:7.10.2"
        );
        assert_eq!(
            source_image(SourceEngine::OpenSearch, "2.15.0"),
            "opensearchproject/opensearch:2.15.0"
        );
        assert_eq!(source_image(SourceEngine::Solr, "9.7.0"), "solr:9.7.0");
        assert_eq!(target_image("3.3.0"), "opensearchproject/opensearch:3.3.0");
    }

    #[test]
    fn kind_config_maps_ports() {
        let cfg = kind_config("ma-demo-source", 19200, 30920);
        assert!(cfg.contains("name: ma-demo-source"));
        assert!(cfg.contains("hostPort: 19200"));
        assert!(cfg.contains("containerPort: 30920"));
        assert!(cfg.contains("kind: Cluster"));
    }

    #[test]
    fn http_source_embeds_image_and_env() {
        let y = http_source(&es_answers());
        assert!(y.contains("docker.elastic.co/elasticsearch/elasticsearch:7.10.2"));
        assert!(y.contains("discovery.type"));
        assert!(y.contains("xpack.security.enabled"));
        assert!(y.contains("nodePort: 30920"));
        assert!(y.contains("kind: StatefulSet"));
        // No plugins requested → no command override (default entrypoint runs).
        assert!(!y.contains("command:"));
    }

    #[test]
    fn http_source_emits_install_then_exec_command_when_plugins_requested() {
        let mut a = es_answers();
        a.source_plugins = vec!["repository-s3".into(), "analysis-icu".into()];
        let y = http_source(&a);
        // Command override installs the plugins then execs the ES entrypoint.
        assert!(y.contains("command: [\"sh\", \"-c\","));
        assert!(y.contains("elasticsearch-plugin install --batch repository-s3"));
        assert!(y.contains("analysis-icu"));
        assert!(y.contains("exec /usr/local/bin/docker-entrypoint.sh eswrapper"));
    }

    #[test]
    fn opensearch_source_uses_os_plugin_cli_and_entrypoint() {
        let mut a = Answers::new();
        a.source_engine = Some(SourceEngine::OpenSearch);
        a.source_version = Some("2.15.0".into());
        a.source_plugins = vec!["analysis-icu".into()];
        let y = http_source(&a);
        assert!(y.contains("opensearch-plugin install --batch analysis-icu"));
        assert!(y.contains("exec ./opensearch-docker-entrypoint.sh"));
        assert!(y.contains("DISABLE_SECURITY_PLUGIN"));
        assert!(y.contains("opensearchproject/opensearch:2.15.0"));
    }

    #[test]
    fn solr_source_uses_solr_image_and_precreate() {
        let y = solr_source("9.7.0");
        assert!(y.contains("image: solr:9.7.0"));
        assert!(y.contains("solr-precreate"));
        assert!(y.contains("nodePort: 30983"));
    }

    #[test]
    fn source_dispatches_by_engine() {
        let mut solr = Answers::new();
        solr.source_engine = Some(SourceEngine::Solr);
        solr.source_version = Some("8.11.3".into());
        assert!(source(&solr).contains("solr:8.11.3"));
        assert!(source(&es_answers()).contains("elasticsearch:7.10.2"));
    }

    #[test]
    fn target_manifest_has_opensearch_image() {
        let y = target("3.3.0");
        assert!(y.contains("opensearchproject/opensearch:3.3.0"));
        assert!(y.contains("name: target-opensearch"));
    }

    #[test]
    fn localstack_exposes_s3_edge_port() {
        let y = localstack();
        assert!(y.contains("localstack/localstack:4.3.0"));
        assert!(y.contains("4566"));
        assert!(y.contains("value: \"s3\""));
    }

    #[test]
    fn locust_embeds_indented_locustfile_and_host() {
        let y = locust("source-elasticsearch");
        assert!(y.contains("locustio/locust:2.31.8"));
        assert!(y.contains("http://source-elasticsearch:9200"));
        // ConfigMap data block carries the python, indented under the `|`.
        assert!(y.contains("locustfile.py: |"));
        assert!(y.contains("class SearchUser"));
        assert!(y.contains("    from locust import"));
    }

    #[test]
    fn sample_app_targets_source_host() {
        let y = sample_search_app("source-opensearch");
        assert!(y.contains("busybox:1.36"));
        assert!(y.contains("source-opensearch:9200"));
    }

    #[test]
    fn data_seed_job_bulk_loads_source_over_rest() {
        let y = data_seed_job("source-elasticsearch");
        // Self-contained curl-based bulk loader (no console image, which needs a
        // migration config). Waits for the source, then _bulk-loads demo-logs.
        assert!(y.contains("curlimages/curl:8.10.1"));
        assert!(y.contains("http://source-elasticsearch:9200/demo-logs/_bulk"));
        assert!(y.contains("kind: Job"));
    }

    #[test]
    fn client_manifests_reflect_selection() {
        let mut a = es_answers();
        a.clients = vec![ClientApp::Locust];
        let m = client_manifests(&a, "source-elasticsearch");
        assert_eq!(m.len(), 1);
        assert_eq!(m[0].0, "locust");

        a.clients = vec![ClientApp::Locust, ClientApp::SampleSearchApp];
        assert_eq!(client_manifests(&a, "source-elasticsearch").len(), 2);

        a.clients = vec![];
        assert!(client_manifests(&a, "source-elasticsearch").is_empty());
    }

    #[test]
    fn needs_localstack_only_for_localstack_choice() {
        let mut a = es_answers();
        a.snapshot_storage = Some(SnapshotStorage::LocalStack);
        assert!(needs_localstack(&a));
        a.snapshot_storage = Some(SnapshotStorage::None);
        assert!(!needs_localstack(&a));
        a.snapshot_storage = Some(SnapshotStorage::AwsS3);
        assert!(!needs_localstack(&a));
    }

    #[test]
    fn namespace_manifest_is_well_formed() {
        let _ = TargetMode::Provision; // keep import used across cfg
        let y = namespace();
        assert!(y.contains("kind: Namespace"));
        assert!(y.contains("name: ma-demo"));
    }
}
